### PR TITLE
updated version.

### PR DESCRIPTION
**Pull request by SilasK**
Hey @chris-rands This seems like I many changes, but actually I just took the snakemake-workflow template. (see commit message)

What is the reason why you use the rather cumbersome absolute paths? 
I can show you the conda magic and some other changes I did. when are you here today?

### CODE REVIEW

**Comment by chris-rands** [comment]
Thanks for this, as I said I'm in flavor of updating the to the proper snakemake style (although I am not familiar with it yet), but the `README.md` and documentation at the top of the `Snakefile` are now outdated, can update them? Also did you mention you wrote some tests somewhere? I notice you deleted my sample data, but I think it would be good to keep it with an example command so that the pipeline can be ran as before to produce the same sample outputs?

**Comment by SilasK** [comment]
Test and your sample data are in .test subdirectory, which is hifdden. So
everithng is there.

You can run

cd .test
./test.sh -n

**Comment by chris-rands** [comment]
Sorry I can't see `.test` directory, are you sure you committed the files or am I missing something? Either way, would be good to update the relevant `README.md` and `Snakefile` text to ensure it's all documented correctly

**Comment by SilasK** [comment]
Ah, sorry, I think the .gitignore blocks the sync. Sorry.

**Comment by chris-rands** [comment]
thanks Silas

**Pull request merged**
